import type { HadithCollection } from '../types/hadith.js'

// Omit 'id' since these are constant definitions without DB IDs
type CollectionDef = Omit<HadithCollection, 'id'>

export const HADITH_COLLECTIONS: CollectionDef[] = [
  // ── Sunni: Kutub al-Sittah (Six canonical books) ──────────────────────────
  {
    key: 'bukhari',
    nameArabic: 'صحيح البخاري',
    nameEnglish: 'Sahih al-Bukhari',
    tradition: 'sunni',
    tier: 'primary',
    compiler: 'Muhammad ibn Ismail al-Bukhari',
    century: 3,
  },
  {
    key: 'muslim',
    nameArabic: 'صحيح مسلم',
    nameEnglish: 'Sahih Muslim',
    tradition: 'sunni',
    tier: 'primary',
    compiler: 'Muslim ibn al-Hajjaj',
    century: 3,
  },
  {
    key: 'abu-dawud',
    nameArabic: 'سنن أبي داود',
    nameEnglish: 'Sunan Abu Dawud',
    tradition: 'sunni',
    tier: 'primary',
    compiler: 'Abu Dawud al-Sijistani',
    century: 3,
  },
  {
    key: 'tirmidhi',
    nameArabic: 'جامع الترمذي',
    nameEnglish: "Jami' at-Tirmidhi",
    tradition: 'sunni',
    tier: 'primary',
    compiler: 'Muhammad ibn Isa at-Tirmidhi',
    century: 3,
  },
  {
    key: 'nasai',
    nameArabic: 'سنن النسائي',
    nameEnglish: "Sunan an-Nasa'i",
    tradition: 'sunni',
    tier: 'primary',
    compiler: "Ahmad ibn Shu'ayb an-Nasa'i",
    century: 3,
  },
  {
    key: 'ibn-majah',
    nameArabic: 'سنن ابن ماجه',
    nameEnglish: 'Sunan Ibn Majah',
    tradition: 'sunni',
    tier: 'primary',
    compiler: 'Muhammad ibn Yazid Ibn Majah',
    century: 3,
  },

  // ── Sunni: Extended primary ────────────────────────────────────────────────
  {
    key: 'malik',
    nameArabic: 'موطأ مالك',
    nameEnglish: "Muwatta' Imam Malik",
    tradition: 'sunni',
    tier: 'primary',
    compiler: 'Malik ibn Anas',
    century: 2,
  },
  {
    key: 'ahmad',
    nameArabic: 'مسند أحمد',
    nameEnglish: 'Musnad Ahmad',
    tradition: 'sunni',
    tier: 'primary',
    compiler: 'Ahmad ibn Hanbal',
    century: 3,
  },
  {
    key: 'darimi',
    nameArabic: 'سنن الدارمي',
    nameEnglish: 'Sunan ad-Darimi',
    tradition: 'sunni',
    tier: 'primary',
    compiler: 'Abdullah ibn Abd ar-Rahman ad-Darimi',
    century: 3,
  },

  // ── Sunni: Secondary / Commentary ─────────────────────────────────────────
  {
    key: 'bayhaqi',
    nameArabic: 'السنن الكبرى للبيهقي',
    nameEnglish: 'Sunan al-Kubra (al-Bayhaqi)',
    tradition: 'sunni',
    tier: 'secondary',
    compiler: 'Ahmad ibn al-Husayn al-Bayhaqi',
    century: 5,
  },
  {
    key: 'tabarani',
    nameArabic: 'المعجم الكبير للطبراني',
    nameEnglish: 'al-Mu\'jam al-Kabir (at-Tabarani)',
    tradition: 'sunni',
    tier: 'secondary',
    compiler: 'Sulayman ibn Ahmad at-Tabarani',
    century: 4,
  },
  {
    key: 'hakim',
    nameArabic: 'المستدرك على الصحيحين',
    nameEnglish: 'al-Mustadrak (al-Hakim)',
    tradition: 'sunni',
    tier: 'secondary',
    compiler: 'Muhammad ibn Abdullah al-Hakim',
    century: 4,
  },
  {
    key: 'ibn-hibban',
    nameArabic: 'صحيح ابن حبان',
    nameEnglish: 'Sahih Ibn Hibban',
    tradition: 'sunni',
    tier: 'secondary',
    compiler: 'Muhammad ibn Hibban',
    century: 4,
  },
  {
    key: 'riyadh-salihin',
    nameArabic: 'رياض الصالحين',
    nameEnglish: 'Riyad as-Salihin',
    tradition: 'sunni',
    tier: 'commentary',
    compiler: 'Yahya ibn Sharaf an-Nawawi',
    century: 7,
  },
  {
    key: 'nawawi-40',
    nameArabic: 'الأربعون النووية',
    nameEnglish: "Al-Nawawi's Forty Hadith",
    tradition: 'sunni',
    tier: 'commentary',
    compiler: 'Yahya ibn Sharaf an-Nawawi',
    century: 7,
  },
  {
    key: 'bulugh-maram',
    nameArabic: 'بلوغ المرام',
    nameEnglish: 'Bulugh al-Maram',
    tradition: 'sunni',
    tier: 'commentary',
    compiler: 'Ibn Hajar al-Asqalani',
    century: 9,
  },

  // ── Shia: al-Kutub al-Arba'ah (Four books) ────────────────────────────────
  {
    key: 'kafi',
    nameArabic: 'الكافي',
    nameEnglish: 'al-Kafi',
    tradition: 'shia',
    tier: 'primary',
    compiler: 'Muhammad ibn Yaqub al-Kulayni',
    century: 4,
  },
  {
    key: 'man-la-yahduruhu',
    nameArabic: 'من لا يحضره الفقيه',
    nameEnglish: 'Man la Yahduruhu al-Faqih',
    tradition: 'shia',
    tier: 'primary',
    compiler: 'Muhammad ibn Ali ibn Babawayh (al-Shaykh al-Saduq)',
    century: 4,
  },
  {
    key: 'tahdhib-ahkam',
    nameArabic: 'تهذيب الأحكام',
    nameEnglish: 'Tahdhib al-Ahkam',
    tradition: 'shia',
    tier: 'primary',
    compiler: 'Muhammad ibn al-Hasan al-Tusi',
    century: 5,
  },
  {
    key: 'istibsar',
    nameArabic: 'الاستبصار',
    nameEnglish: 'al-Istibsar',
    tradition: 'shia',
    tier: 'primary',
    compiler: 'Muhammad ibn al-Hasan al-Tusi',
    century: 5,
  },

  // ── Ibadi ──────────────────────────────────────────────────────────────────
  {
    key: 'musnad-rabi',
    nameArabic: 'مسند الربيع بن حبيب',
    nameEnglish: "Musnad ar-Rabi' ibn Habib",
    tradition: 'ibadi',
    tier: 'primary',
    compiler: "ar-Rabi' ibn Habib al-Farahidi",
    century: 2,
  },
  {
    key: 'jami-ibn-jafar',
    nameArabic: 'الجامع لابن جعفر',
    nameEnglish: 'al-Jami (Ibn Jafar)',
    tradition: 'ibadi',
    tier: 'secondary',
    compiler: 'Muhammad ibn Jafar al-Izkawi',
    century: 4,
  },
]
